---
- hosts: all
  become: 'true'
  gather_facts: 'false'
  tasks:
    - name: Update all packages on the system
      openbsd_pkg:
        name: '*'
        state: latest
    - name: Install required packages
      become: 'true'
      openbsd_pkg:
        state: present
        name:
          - 'vim--no_x11'
          - 'bash--'
          - 'bzip2--'
          - 'curl--'
          - 'gd--'
          - 'git--'
          - 'gmp--'
          - 'libxml--'
          - 'libxslt--'
          - 'mpfr--'
          - 'ntp--'
          - 'quirks--'
          - 'sqlite3--'
          - 'tidyp--'
          - 'unzip--iconv'
          - tree
          - p5-YAML-XS
          - p5-Net-SSLeay
          - p5-Moo
          - p5-Moose
          - p5-IO-Socket-SSL
          - p5-Log-Log4perl
          - p5-Proc-ProcessTable
          - p5-MooseX-Types
          - p5-MooseX-Types-LoadableClass
          - p5-MooseX-Types-Path-Class
          - p5-DateTime
          - p5-DateTime-Format-Strptime
          - p5-DateTime-Format-SQLite
          - p5-DateTime-Format-MySQL
          - p5-Class-DBI
          - p5-Text-CSV
          - p5-Text-CSV_XS
          - p5-Test-EOL
          - p5-Test-NoTabs
          - p5-JSON-DWIW
          - p5-Time-Piece-MySQL
          - p5-SQL-Translator
          - p5-JSON-Any
          - p5-Module-Pluggable
          - p5-Getopt-Long-Descriptive
          - p5-Archive-Zip
          - p5-Filesys-Df
    - name: Add the user to run the smoker
      block:
        - name: Add user group
          ansible.builtin.group:
            name: '{{ cpan_user }}'
            state: present
        - name: Add user
          ansible.builtin.user:
            name: '{{ cpan_user }}'
            comment: The user that runs the CPAN-Reporter-Smoker
            create_home: 'true'
            home: '/home/{{ cpan_user }}'
            state: present
            group: '{{ cpan_user }}'
            groups:
              - testers
        - name: Configure access through SSH
          ansible.posix.authorized_key:
            user: '{{ cpan_user }}'
            state: present
            key: "{{ lookup('file', cpan_user_pub_key) }}"
    - name: Create the cpan client directory
      file:
        path: '/home/{{ cpan_user }}/.cpan/CPAN'
        state: directory
        owner: '{{ cpan_user }}'
        group: '{{ cpan_user }}'
        mode: '0755'
    - name: Configure the cpan client
      template:
        src: MyConfig.pm.j2
        dest: '/home/{{ cpan_user }}/.cpan/CPAN/MyConfig.pm'
        owner: '{{ cpan_user }}'
        mode: '0644'
        group: '{{ cpan_user }}'
    - name: Configure ksh
      template:
        src: profile.j2
        dest: '/home/{{ cpan_user }}/.profile'
        owner: '{{ cpan_user }}'
        mode: '0644'
        group: '{{ cpan_user }}'
    - name: Configure CPAN::Reporter
      block:
        - name: Configuration directory
          file:
            path: '/home/{{ cpan_user }}/.cpanreporter'
            state: directory
            owner: '{{ cpan_user }}'
            group: '{{ cpan_user }}'
            mode: '0755'
        - name: Configuration file
          template:
            src: config.ini.j2
            dest: '/home/{{ cpan_user }}/.cpanreporter/config.ini'
            owner: '{{ cpan_user }}'
            mode: '0644'
            group: '{{ cpan_user }}'
        - name: Sent reports directory
          file:
            path: '/home/{{ cpan_user }}/ready_reports'
            state: directory
            owner: '{{ cpan_user }}'
            group: '{{ cpan_user }}'
            mode: '0755'
