---
# This software is copyright (c) 2017 of Alceu Rodrigues de Freitas Junior,
# arfreitas@cpan.org
#
# This file is part of CPAN OpenBSD Smoker.
#
# CPAN OpenBSD Smoker is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# CPAN OpenBSD Smoker is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CPAN OpenBSD Smoker.  If not, see http://www.gnu.org/licenses.

- hosts: all
  become: 'true'
  gather_facts: 'false'
  tasks:
    - name: Update all packages on the system
      openbsd_pkg:
        name: '*'
        state: latest
    - name: Install required packages
      become: 'true'
      openbsd_pkg:
        state: present
        name:
          - 'vim--no_x11'
          - 'bash--'
          - 'bzip2--'
          - 'curl--'
          - 'gd--'
          - 'git--'
          - 'gmp--'
          - 'libxml--'
          - 'libxslt--'
          - 'mpfr--'
          - 'ntp--'
          - 'quirks--'
          - 'sqlite3--'
          - 'tidyp--'
          - 'unzip--iconv'
          - tree
          - p5-YAML-XS
          - p5-Net-SSLeay
          - p5-Moo
          - p5-Moose
          - p5-IO-Socket-SSL
          - p5-Log-Log4perl
          - p5-Proc-ProcessTable
          - p5-MooseX-Types
          - p5-MooseX-Types-LoadableClass
          - p5-MooseX-Types-Path-Class
          - p5-DateTime
          - p5-DateTime-Format-Strptime
          - p5-DateTime-Format-SQLite
          - p5-DateTime-Format-MySQL
          - p5-Class-DBI
          - p5-JSON-DWIW
          - p5-Time-Piece-MySQL
          - p5-SQL-Translator
          - p5-JSON-Any
          - p5-Module-Pluggable
          - p5-Getopt-Long-Descriptive
          - p5-Archive-Zip
          - p5-Filesys-Df
          - p5-Text-CSV
          - p5-Text-CSV_XS
          - p5-Test-API
          - p5-Test-Assertions
          - p5-Test-Base
          - p5-Test-Bits
          - p5-Test-CPAN-Meta
          - p5-Test-CheckManifest
          - p5-Test-Class
          - p5-Test-ClassAPI
          - p5-Test-CleanNamespaces
          - p5-Test-Cmd
          - p5-Test-Command
          - p5-Test-Command-Simple
          - p5-Test-Compile
          - p5-Test-Corpus-Audio-MPD
          - p5-Test-Deep
          - p5-Test-Deep-Fuzzy
          - p5-Test-Deep-JSON
          - p5-Test-Deep-Type
          - p5-Test-Differences
          - p5-Test-DistManifest
          - p5-Test-Distribution
          - p5-Test-EOL
          - p5-Test-Exception
          - p5-Test-Exit
          - p5-Test-Expect
          - p5-Test-FailWarnings
          - p5-Test-Fatal
          - p5-Test-File
          - p5-Test-File-Contents
          - p5-Test-File-ShareDir
          - p5-Test-Group
          - p5-Test-HTML-Tidy
          - p5-Test-HTTP-LocalServer
          - p5-Test-HTTP-Server-Simple
          - p5-Test-HasVersion
          - p5-Test-HexDifferences
          - p5-Test-Inline
          - p5-Test-Inter
          - p5-Test-JSON
          - p5-Test-LWP-UserAgent
          - p5-Test-LeakTrace
          - p5-Test-LectroTest
          - p5-Test-Lib
          - p5-Test-LongString
          - p5-Test-Manifest
          - p5-Test-Memory-Cycle
          - p5-Test-MockModule
          - p5-Test-MockObject
          - p5-Test-MockRandom
          - p5-Test-MockSleep
          - p5-Test-MockTime
          - p5-Test-Modern
          - p5-Test-More-UTF8
          - p5-Test-Most
          - p5-Test-Needs
          - p5-Test-NoTabs
          - p5-Test-NoWarnings
          - p5-Test-Number-Delta
          - p5-Test-Object
          - p5-Test-Output
          - p5-Test-POE-Server-TCP
          - p5-Test-Perl-Critic
          - p5-Test-Pod
          - p5-Test-Pod-Content
          - p5-Test-Pod-Coverage
          - p5-Test-Portability-Files
          - p5-Test-Regexp
          - p5-Test-Reporter
          - p5-Test-Requires
          - p5-Test-RequiresInternet
          - p5-Test-Script
          - p5-Test-SharedFork
          - p5-Test-Spec
          - p5-Test-Spelling
          - p5-Test-Strict
          - p5-Test-SubCalls
          - p5-Test-TCP
          - p5-Test-Taint
          - p5-Test-TempDir
          - p5-Test-Time
          - p5-Test-TrailingSpace
          - p5-Test-Trap
          - p5-Test-URI
          - p5-Test-Unit
          - p5-Test-UseAllModules
          - p5-Test-Version
          - p5-Test-WWW-Mechanize
          - p5-Test-WWW-Mechanize-Catalyst
          - p5-Test-Warn
          - p5-Test-Warnings
          - p5-Test-Weaken
          - p5-Test-Without-Module
          - p5-Test-XML
          - p5-Test-YAML
          - p5-Test-YAML-Valid
          - p5-Test-utf8
    - name: Copy smoker_install script
      ansible.builtin.copy:
        state: present
        src: scripts/smoker_install
        dest: /usr/local/bin/smoker_install
        owner: root
        group: testers
        mode: '0555'
    - name: Add the user to run the smoker
      block:
        - name: Add user group
          ansible.builtin.group:
            name: '{{ cpan_user }}'
            state: present
        - name: Add user
          ansible.builtin.user:
            name: '{{ cpan_user }}'
            comment: The user that runs the CPAN-Reporter-Smoker
            create_home: 'true'
            home: '/home/{{ cpan_user }}'
            state: present
            group: '{{ cpan_user }}'
            groups:
              - testers
        - name: Configure access through SSH
          ansible.posix.authorized_key:
            user: '{{ cpan_user }}'
            state: present
            key: "{{ lookup('file', cpan_user_pub_key) }}"
    - name: Create the cpan client directory
      file:
        path: '/home/{{ cpan_user }}/.cpan/CPAN'
        state: directory
        owner: '{{ cpan_user }}'
        group: '{{ cpan_user }}'
        mode: '0755'
    - name: Configure the cpan client
      template:
        src: MyConfig.pm.j2
        dest: '/home/{{ cpan_user }}/.cpan/CPAN/MyConfig.pm'
        owner: '{{ cpan_user }}'
        mode: '0644'
        group: '{{ cpan_user }}'
    - name: Configure ksh
      template:
        src: profile.j2
        dest: '/home/{{ cpan_user }}/.profile'
        owner: '{{ cpan_user }}'
        mode: '0644'
        group: '{{ cpan_user }}'
    - name: Configure CPAN::Reporter
      block:
        - name: Configuration directory
          file:
            path: '/home/{{ cpan_user }}/.cpanreporter'
            state: directory
            owner: '{{ cpan_user }}'
            group: '{{ cpan_user }}'
            mode: '0755'
        - name: Configuration file
          template:
            src: config.ini.j2
            dest: '/home/{{ cpan_user }}/.cpanreporter/config.ini'
            owner: '{{ cpan_user }}'
            mode: '0644'
            group: '{{ cpan_user }}'
        - name: Sent reports directory
          file:
            path: '/home/{{ cpan_user }}/ready_reports'
            state: directory
            owner: '{{ cpan_user }}'
            group: '{{ cpan_user }}'
            mode: '0755'
