---
'on':
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Lint CPAN distroprefs files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: super-linter/super-linter/slim@v5
        env:
          VALIDATE_YAML: true
          VALIDATE_ALL_CODEBASE: true
